config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
     @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "Error"
      render :edit
    end
  end
  
  def create
  	@book = Book.new(book_params)
  	if @book.save
  		flash[:notice] = "Book was successfully added！"
	  	redirect_to book_path(@book.id)
  	else
  		@books = Book.all
  		render :index
  	end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "destroied successfully "
    redirect_to ("/books")
  end
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_error_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <% if @book.errors.any? %>
      <div="er_message">
      <h2 class="er_txt"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<!DOCTYPE>
<html>
    <meta charset="UTF-8">
<h1>Editing Book</h1>

<%= render 'error_form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</html>

app/views/books/index.html.erb
<html>
  <body>
<% if flash[:notice] %>
	<p id="notice"><b><%= flash[:notice] %></b></p>
<% end %>
<h1>Books</h1>

<table>
  <thead>
    <tr class="table_title">
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr class="table_body">
        <td class="b-title"><%= book.title %></td>
        <td class="b-body"><%= book.body %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to "Destroy", "/books/#{book.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2>New book</h2>
	<%= form_for(@book) do |f| %>
  <%= render 'error_form', book: @book %>
<% end %>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
    <head>
  <% if flash[:notice] %>
	  <p><b><%= flash[:notice] %></b></p>
  <% end %>
    
    <title>WebCampBackendNew</title>
    </head>
  <body>
    <p id="notice"></p>

<p>
  <strong>Title:</strong>
  <%= @book.title%>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body%>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<a class="back" href="/books">Back</a>

  

</body>
</html>

app/views/home/top.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title>WebCampBackendNew</title>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
    <p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>    	
  

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/error_messages.html.haml
layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message